import type { DonationCategoryMeta, DonationItemEntry, DepreciationSchedule, DonationCategory } from '../types/index.js';

/** Year the charity guide data was transcribed from. */
export const DONATION_DB_SOURCE_YEAR = 2024;

export const DONATION_CATEGORIES: DonationCategoryMeta[] = [
  { id: 'clothing_mens', label: "Men's Clothing" },
  { id: 'clothing_womens', label: "Women's Clothing" },
  { id: 'clothing_childrens', label: "Children's Clothing" },
  { id: 'furniture', label: 'Furniture' },
  { id: 'electronics', label: 'Electronics' },
  { id: 'appliances_small', label: 'Small Appliances' },
  { id: 'appliances_large', label: 'Large Appliances' },
  { id: 'kitchen', label: 'Kitchen & Dining' },
  { id: 'sports_recreation', label: 'Sports & Recreation' },
  { id: 'toys_games', label: 'Toys & Games' },
  { id: 'books_media', label: 'Books & Media' },
  { id: 'household', label: 'Household Items' },
  { id: 'miscellaneous', label: 'Miscellaneous' },
];

// ─── Seed Database ──────────────────────────────────────────
// Sources: Salvation Army Valuation Guide (2024), Goodwill Valuation Guide (2024)
// ~170 items, deduplicated across guides

export const DONATION_ITEMS: DonationItemEntry[] = [
  // ── Men's Clothing ──────────────────────────────────────
  { id: 'mc-001', name: 'Suit (2-piece)', category: 'clothing_mens', lowFMV: 25, highFMV: 95, source: 'salvation_army', keywords: ['blazer', 'jacket', 'pants', 'dress suit'] },
  { id: 'mc-002', name: 'Sport Coat / Blazer', category: 'clothing_mens', lowFMV: 12, highFMV: 60, source: 'salvation_army', keywords: ['blazer', 'sport jacket'] },
  { id: 'mc-003', name: 'Overcoat', category: 'clothing_mens', lowFMV: 20, highFMV: 80, source: 'salvation_army', keywords: ['coat', 'winter coat', 'topcoat'] },
  { id: 'mc-004', name: 'Raincoat', category: 'clothing_mens', lowFMV: 10, highFMV: 50, source: 'salvation_army' },
  { id: 'mc-005', name: 'Sweater', category: 'clothing_mens', lowFMV: 5, highFMV: 25, source: 'salvation_army', keywords: ['pullover', 'cardigan'] },
  { id: 'mc-006', name: 'Shirt (dress)', category: 'clothing_mens', lowFMV: 4, highFMV: 18, source: 'salvation_army', keywords: ['dress shirt', 'button down', 'button-down'] },
  { id: 'mc-007', name: 'Shirt (casual / sport)', category: 'clothing_mens', lowFMV: 3, highFMV: 12, source: 'salvation_army', keywords: ['polo', 'sport shirt', 'casual shirt'] },
  { id: 'mc-008', name: 'T-Shirt', category: 'clothing_mens', lowFMV: 1, highFMV: 6, source: 'goodwill', keywords: ['tee', 'tshirt'] },
  { id: 'mc-009', name: 'Pants (dress)', category: 'clothing_mens', lowFMV: 6, highFMV: 25, source: 'salvation_army', keywords: ['trousers', 'slacks', 'dress pants'] },
  { id: 'mc-010', name: 'Pants (casual)', category: 'clothing_mens', lowFMV: 5, highFMV: 15, source: 'salvation_army', keywords: ['khakis', 'chinos'] },
  { id: 'mc-011', name: 'Jeans', category: 'clothing_mens', lowFMV: 5, highFMV: 20, source: 'salvation_army', keywords: ['denim'] },
  { id: 'mc-012', name: 'Shorts', category: 'clothing_mens', lowFMV: 3, highFMV: 10, source: 'salvation_army' },
  { id: 'mc-013', name: 'Shoes (dress)', category: 'clothing_mens', lowFMV: 8, highFMV: 35, source: 'salvation_army', keywords: ['oxfords', 'loafers'] },
  { id: 'mc-014', name: 'Shoes (casual / athletic)', category: 'clothing_mens', lowFMV: 4, highFMV: 25, source: 'salvation_army', keywords: ['sneakers', 'tennis shoes', 'running shoes'] },
  { id: 'mc-015', name: 'Boots', category: 'clothing_mens', lowFMV: 8, highFMV: 40, source: 'salvation_army', keywords: ['work boots', 'hiking boots'] },
  { id: 'mc-016', name: 'Jacket (light)', category: 'clothing_mens', lowFMV: 8, highFMV: 35, source: 'salvation_army', keywords: ['windbreaker', 'light jacket'] },
  { id: 'mc-017', name: 'Down Jacket', category: 'clothing_mens', lowFMV: 15, highFMV: 60, source: 'goodwill', keywords: ['puffer', 'winter jacket'] },
  { id: 'mc-018', name: 'Tie', category: 'clothing_mens', lowFMV: 2, highFMV: 8, source: 'salvation_army', keywords: ['necktie'] },
  { id: 'mc-019', name: 'Belt', category: 'clothing_mens', lowFMV: 2, highFMV: 10, source: 'goodwill' },
  { id: 'mc-020', name: 'Bathrobe', category: 'clothing_mens', lowFMV: 4, highFMV: 15, source: 'salvation_army', keywords: ['robe'] },
  { id: 'mc-021', name: 'Pajamas', category: 'clothing_mens', lowFMV: 3, highFMV: 10, source: 'salvation_army', keywords: ['sleepwear'] },
  { id: 'mc-022', name: 'Swim Trunks', category: 'clothing_mens', lowFMV: 3, highFMV: 10, source: 'goodwill', keywords: ['swimsuit', 'swimming'] },
  { id: 'mc-023', name: 'Hat / Cap', category: 'clothing_mens', lowFMV: 2, highFMV: 8, source: 'goodwill', keywords: ['baseball cap'] },
  { id: 'mc-024', name: 'Gloves', category: 'clothing_mens', lowFMV: 3, highFMV: 10, source: 'salvation_army' },
  { id: 'mc-025', name: 'Scarf', category: 'clothing_mens', lowFMV: 3, highFMV: 10, source: 'salvation_army' },

  // ── Women's Clothing ────────────────────────────────────
  { id: 'wc-001', name: 'Dress (casual)', category: 'clothing_womens', lowFMV: 6, highFMV: 28, source: 'salvation_army', keywords: ['sundress'] },
  { id: 'wc-002', name: 'Dress (evening / formal)', category: 'clothing_womens', lowFMV: 15, highFMV: 90, source: 'salvation_army', keywords: ['gown', 'cocktail dress', 'formal dress'] },
  { id: 'wc-003', name: 'Suit (2-piece)', category: 'clothing_womens', lowFMV: 15, highFMV: 70, source: 'salvation_army', keywords: ['pantsuit', 'skirt suit'] },
  { id: 'wc-004', name: 'Blouse', category: 'clothing_womens', lowFMV: 4, highFMV: 18, source: 'salvation_army', keywords: ['top'] },
  { id: 'wc-005', name: 'Sweater', category: 'clothing_womens', lowFMV: 5, highFMV: 20, source: 'salvation_army', keywords: ['pullover', 'cardigan'] },
  { id: 'wc-006', name: 'Skirt', category: 'clothing_womens', lowFMV: 4, highFMV: 18, source: 'salvation_army' },
  { id: 'wc-007', name: 'Pants / Slacks', category: 'clothing_womens', lowFMV: 5, highFMV: 20, source: 'salvation_army', keywords: ['trousers'] },
  { id: 'wc-008', name: 'Jeans', category: 'clothing_womens', lowFMV: 5, highFMV: 20, source: 'salvation_army', keywords: ['denim'] },
  { id: 'wc-009', name: 'Shorts', category: 'clothing_womens', lowFMV: 3, highFMV: 10, source: 'salvation_army' },
  { id: 'wc-010', name: 'Coat (winter)', category: 'clothing_womens', lowFMV: 18, highFMV: 75, source: 'salvation_army', keywords: ['winter coat', 'overcoat'] },
  { id: 'wc-011', name: 'Jacket (light)', category: 'clothing_womens', lowFMV: 8, highFMV: 30, source: 'salvation_army', keywords: ['windbreaker'] },
  { id: 'wc-012', name: 'Down Jacket', category: 'clothing_womens', lowFMV: 15, highFMV: 55, source: 'goodwill', keywords: ['puffer'] },
  { id: 'wc-013', name: 'Raincoat', category: 'clothing_womens', lowFMV: 8, highFMV: 35, source: 'salvation_army' },
  { id: 'wc-014', name: 'Shoes (dress)', category: 'clothing_womens', lowFMV: 6, highFMV: 30, source: 'salvation_army', keywords: ['heels', 'pumps'] },
  { id: 'wc-015', name: 'Shoes (casual / athletic)', category: 'clothing_womens', lowFMV: 4, highFMV: 22, source: 'salvation_army', keywords: ['sneakers', 'flats'] },
  { id: 'wc-016', name: 'Boots', category: 'clothing_womens', lowFMV: 8, highFMV: 40, source: 'salvation_army' },
  { id: 'wc-017', name: 'Handbag / Purse', category: 'clothing_womens', lowFMV: 4, highFMV: 25, source: 'salvation_army', keywords: ['purse', 'bag', 'pocketbook'] },
  { id: 'wc-018', name: 'Bathrobe', category: 'clothing_womens', lowFMV: 4, highFMV: 15, source: 'salvation_army', keywords: ['robe'] },
  { id: 'wc-019', name: 'Pajamas / Nightgown', category: 'clothing_womens', lowFMV: 3, highFMV: 12, source: 'salvation_army', keywords: ['sleepwear', 'nightwear'] },
  { id: 'wc-020', name: 'Swimsuit', category: 'clothing_womens', lowFMV: 4, highFMV: 14, source: 'goodwill', keywords: ['bathing suit', 'bikini'] },
  { id: 'wc-021', name: 'Scarf', category: 'clothing_womens', lowFMV: 3, highFMV: 12, source: 'salvation_army' },
  { id: 'wc-022', name: 'Hat', category: 'clothing_womens', lowFMV: 3, highFMV: 10, source: 'goodwill' },
  { id: 'wc-023', name: 'Gloves', category: 'clothing_womens', lowFMV: 3, highFMV: 10, source: 'salvation_army' },
  { id: 'wc-024', name: 'T-Shirt', category: 'clothing_womens', lowFMV: 1, highFMV: 6, source: 'goodwill', keywords: ['tee'] },

  // ── Children's Clothing ─────────────────────────────────
  { id: 'cc-001', name: 'Dress', category: 'clothing_childrens', lowFMV: 3, highFMV: 15, source: 'salvation_army' },
  { id: 'cc-002', name: 'Shirt / Top', category: 'clothing_childrens', lowFMV: 1, highFMV: 6, source: 'salvation_army', keywords: ['tee', 'blouse'] },
  { id: 'cc-003', name: 'Pants', category: 'clothing_childrens', lowFMV: 2, highFMV: 8, source: 'salvation_army', keywords: ['jeans', 'trousers'] },
  { id: 'cc-004', name: 'Shorts', category: 'clothing_childrens', lowFMV: 1, highFMV: 5, source: 'salvation_army' },
  { id: 'cc-005', name: 'Coat / Jacket', category: 'clothing_childrens', lowFMV: 5, highFMV: 25, source: 'salvation_army', keywords: ['winter coat'] },
  { id: 'cc-006', name: 'Sweater', category: 'clothing_childrens', lowFMV: 2, highFMV: 10, source: 'salvation_army' },
  { id: 'cc-007', name: 'Shoes', category: 'clothing_childrens', lowFMV: 3, highFMV: 12, source: 'salvation_army', keywords: ['sneakers'] },
  { id: 'cc-008', name: 'Boots', category: 'clothing_childrens', lowFMV: 4, highFMV: 14, source: 'salvation_army' },
  { id: 'cc-009', name: 'Pajamas', category: 'clothing_childrens', lowFMV: 2, highFMV: 6, source: 'salvation_army', keywords: ['sleepwear'] },
  { id: 'cc-010', name: 'Swimsuit', category: 'clothing_childrens', lowFMV: 2, highFMV: 6, source: 'goodwill' },
  { id: 'cc-011', name: 'Snowsuit', category: 'clothing_childrens', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['snow pants'] },
  { id: 'cc-012', name: 'Hat / Cap', category: 'clothing_childrens', lowFMV: 1, highFMV: 4, source: 'goodwill' },

  // ── Furniture ───────────────────────────────────────────
  { id: 'fu-001', name: 'Sofa / Couch', category: 'furniture', lowFMV: 35, highFMV: 200, source: 'salvation_army', keywords: ['couch', 'loveseat', 'settee'] },
  { id: 'fu-002', name: 'Loveseat', category: 'furniture', lowFMV: 25, highFMV: 150, source: 'goodwill' },
  { id: 'fu-003', name: 'Recliner', category: 'furniture', lowFMV: 25, highFMV: 125, source: 'salvation_army', keywords: ['reclining chair'] },
  { id: 'fu-004', name: 'Armchair', category: 'furniture', lowFMV: 20, highFMV: 100, source: 'salvation_army', keywords: ['chair', 'accent chair'] },
  { id: 'fu-005', name: 'Coffee Table', category: 'furniture', lowFMV: 15, highFMV: 65, source: 'salvation_army' },
  { id: 'fu-006', name: 'End Table / Side Table', category: 'furniture', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['nightstand', 'side table'] },
  { id: 'fu-007', name: 'Dining Table', category: 'furniture', lowFMV: 35, highFMV: 170, source: 'salvation_army', keywords: ['kitchen table'] },
  { id: 'fu-008', name: 'Dining Chair', category: 'furniture', lowFMV: 8, highFMV: 40, source: 'salvation_army', keywords: ['kitchen chair'] },
  { id: 'fu-009', name: 'Dining Set (table + chairs)', category: 'furniture', lowFMV: 75, highFMV: 350, source: 'salvation_army' },
  { id: 'fu-010', name: 'Desk', category: 'furniture', lowFMV: 25, highFMV: 125, source: 'salvation_army', keywords: ['writing desk', 'computer desk'] },
  { id: 'fu-011', name: 'Office Chair', category: 'furniture', lowFMV: 15, highFMV: 60, source: 'goodwill', keywords: ['desk chair'] },
  { id: 'fu-012', name: 'Bookcase / Bookshelf', category: 'furniture', lowFMV: 15, highFMV: 65, source: 'salvation_army', keywords: ['shelf', 'shelving'] },
  { id: 'fu-013', name: 'Dresser / Bureau', category: 'furniture', lowFMV: 20, highFMV: 100, source: 'salvation_army', keywords: ['chest of drawers'] },
  { id: 'fu-014', name: 'Nightstand', category: 'furniture', lowFMV: 10, highFMV: 40, source: 'goodwill', keywords: ['bedside table'] },
  { id: 'fu-015', name: 'Bed Frame (full/queen)', category: 'furniture', lowFMV: 30, highFMV: 150, source: 'salvation_army', keywords: ['bed'] },
  { id: 'fu-016', name: 'Bed Frame (twin)', category: 'furniture', lowFMV: 20, highFMV: 75, source: 'salvation_army' },
  { id: 'fu-017', name: 'Mattress (full/queen)', category: 'furniture', lowFMV: 30, highFMV: 150, source: 'salvation_army' },
  { id: 'fu-018', name: 'Mattress (twin)', category: 'furniture', lowFMV: 20, highFMV: 75, source: 'salvation_army' },
  { id: 'fu-019', name: 'TV Stand / Entertainment Center', category: 'furniture', lowFMV: 15, highFMV: 75, source: 'salvation_army', keywords: ['media console'] },
  { id: 'fu-020', name: 'Filing Cabinet', category: 'furniture', lowFMV: 10, highFMV: 40, source: 'goodwill' },
  { id: 'fu-021', name: 'China Cabinet / Hutch', category: 'furniture', lowFMV: 35, highFMV: 175, source: 'salvation_army', keywords: ['hutch', 'display cabinet'] },
  { id: 'fu-022', name: 'Futon', category: 'furniture', lowFMV: 20, highFMV: 100, source: 'goodwill', keywords: ['sofa bed'] },
  { id: 'fu-023', name: 'Patio Chair', category: 'furniture', lowFMV: 8, highFMV: 30, source: 'goodwill', keywords: ['outdoor chair', 'lawn chair'] },
  { id: 'fu-024', name: 'Patio Table', category: 'furniture', lowFMV: 15, highFMV: 60, source: 'goodwill', keywords: ['outdoor table'] },
  { id: 'fu-025', name: 'Baby Crib', category: 'furniture', lowFMV: 25, highFMV: 100, source: 'salvation_army', keywords: ['crib'] },
  { id: 'fu-026', name: 'Changing Table', category: 'furniture', lowFMV: 15, highFMV: 50, source: 'goodwill' },

  // ── Electronics ─────────────────────────────────────────
  { id: 'el-001', name: 'Television (flat screen)', category: 'electronics', lowFMV: 30, highFMV: 175, source: 'salvation_army', keywords: ['tv', 'flat panel', 'lcd', 'led'] },
  { id: 'el-002', name: 'Computer Monitor', category: 'electronics', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['display', 'screen'] },
  { id: 'el-003', name: 'Desktop Computer', category: 'electronics', lowFMV: 30, highFMV: 150, source: 'salvation_army', keywords: ['pc', 'tower'] },
  { id: 'el-004', name: 'Laptop Computer', category: 'electronics', lowFMV: 30, highFMV: 200, source: 'salvation_army', keywords: ['notebook'] },
  { id: 'el-005', name: 'Tablet', category: 'electronics', lowFMV: 15, highFMV: 100, source: 'goodwill', keywords: ['ipad'] },
  { id: 'el-006', name: 'Printer', category: 'electronics', lowFMV: 5, highFMV: 35, source: 'salvation_army', keywords: ['inkjet', 'laser printer'] },
  { id: 'el-007', name: 'Scanner', category: 'electronics', lowFMV: 5, highFMV: 25, source: 'goodwill' },
  { id: 'el-008', name: 'Stereo System', category: 'electronics', lowFMV: 15, highFMV: 75, source: 'salvation_army', keywords: ['sound system', 'receiver', 'amplifier'] },
  { id: 'el-009', name: 'Speakers (pair)', category: 'electronics', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['bookshelf speakers'] },
  { id: 'el-010', name: 'Bluetooth Speaker', category: 'electronics', lowFMV: 5, highFMV: 30, source: 'goodwill', keywords: ['portable speaker', 'wireless speaker'] },
  { id: 'el-011', name: 'DVD / Blu-ray Player', category: 'electronics', lowFMV: 4, highFMV: 15, source: 'salvation_army', keywords: ['dvd player', 'bluray'] },
  { id: 'el-012', name: 'Game Console', category: 'electronics', lowFMV: 25, highFMV: 150, source: 'salvation_army', keywords: ['playstation', 'xbox', 'nintendo', 'switch', 'ps5', 'video game'] },
  { id: 'el-013', name: 'Camera (digital)', category: 'electronics', lowFMV: 15, highFMV: 100, source: 'salvation_army', keywords: ['digital camera', 'dslr'] },
  { id: 'el-014', name: 'Headphones', category: 'electronics', lowFMV: 3, highFMV: 25, source: 'goodwill', keywords: ['earbuds'] },
  { id: 'el-015', name: 'Router / Modem', category: 'electronics', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['wifi router'] },
  { id: 'el-016', name: 'Streaming Device', category: 'electronics', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['roku', 'fire stick', 'chromecast', 'apple tv'] },

  // ── Small Appliances ────────────────────────────────────
  { id: 'sa-001', name: 'Coffee Maker', category: 'appliances_small', lowFMV: 4, highFMV: 20, source: 'salvation_army', keywords: ['coffeemaker', 'coffee machine'] },
  { id: 'sa-002', name: 'Espresso Machine', category: 'appliances_small', lowFMV: 15, highFMV: 75, source: 'goodwill' },
  { id: 'sa-003', name: 'Toaster', category: 'appliances_small', lowFMV: 3, highFMV: 12, source: 'salvation_army' },
  { id: 'sa-004', name: 'Toaster Oven', category: 'appliances_small', lowFMV: 5, highFMV: 20, source: 'salvation_army' },
  { id: 'sa-005', name: 'Microwave Oven', category: 'appliances_small', lowFMV: 8, highFMV: 35, source: 'salvation_army', keywords: ['microwave'] },
  { id: 'sa-006', name: 'Blender', category: 'appliances_small', lowFMV: 4, highFMV: 18, source: 'salvation_army' },
  { id: 'sa-007', name: 'Food Processor', category: 'appliances_small', lowFMV: 8, highFMV: 35, source: 'salvation_army' },
  { id: 'sa-008', name: 'Stand Mixer', category: 'appliances_small', lowFMV: 20, highFMV: 90, source: 'salvation_army', keywords: ['kitchenaid', 'mixer'] },
  { id: 'sa-009', name: 'Slow Cooker / Crock Pot', category: 'appliances_small', lowFMV: 4, highFMV: 15, source: 'salvation_army', keywords: ['crockpot'] },
  { id: 'sa-010', name: 'Instant Pot / Pressure Cooker', category: 'appliances_small', lowFMV: 10, highFMV: 40, source: 'goodwill', keywords: ['pressure cooker'] },
  { id: 'sa-011', name: 'Iron', category: 'appliances_small', lowFMV: 3, highFMV: 12, source: 'salvation_army', keywords: ['steam iron'] },
  { id: 'sa-012', name: 'Vacuum Cleaner (upright)', category: 'appliances_small', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['vacuum'] },
  { id: 'sa-013', name: 'Vacuum Cleaner (handheld)', category: 'appliances_small', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['dustbuster'] },
  { id: 'sa-014', name: 'Robot Vacuum', category: 'appliances_small', lowFMV: 15, highFMV: 75, source: 'goodwill', keywords: ['roomba'] },
  { id: 'sa-015', name: 'Sewing Machine', category: 'appliances_small', lowFMV: 15, highFMV: 65, source: 'salvation_army' },
  { id: 'sa-016', name: 'Fan (electric)', category: 'appliances_small', lowFMV: 4, highFMV: 15, source: 'salvation_army', keywords: ['box fan', 'pedestal fan'] },
  { id: 'sa-017', name: 'Space Heater', category: 'appliances_small', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['portable heater'] },
  { id: 'sa-018', name: 'Air Purifier', category: 'appliances_small', lowFMV: 10, highFMV: 45, source: 'goodwill' },
  { id: 'sa-019', name: 'Hair Dryer', category: 'appliances_small', lowFMV: 3, highFMV: 12, source: 'goodwill', keywords: ['blow dryer'] },
  { id: 'sa-020', name: 'Electric Kettle', category: 'appliances_small', lowFMV: 3, highFMV: 12, source: 'goodwill' },

  // ── Large Appliances ────────────────────────────────────
  { id: 'la-001', name: 'Refrigerator', category: 'appliances_large', lowFMV: 75, highFMV: 300, source: 'salvation_army', keywords: ['fridge'] },
  { id: 'la-002', name: 'Stove / Range', category: 'appliances_large', lowFMV: 75, highFMV: 250, source: 'salvation_army', keywords: ['oven', 'range'] },
  { id: 'la-003', name: 'Dishwasher', category: 'appliances_large', lowFMV: 50, highFMV: 200, source: 'salvation_army' },
  { id: 'la-004', name: 'Washing Machine', category: 'appliances_large', lowFMV: 60, highFMV: 225, source: 'salvation_army', keywords: ['washer'] },
  { id: 'la-005', name: 'Dryer', category: 'appliances_large', lowFMV: 60, highFMV: 200, source: 'salvation_army' },
  { id: 'la-006', name: 'Freezer (chest)', category: 'appliances_large', lowFMV: 50, highFMV: 175, source: 'salvation_army', keywords: ['chest freezer', 'deep freezer'] },
  { id: 'la-007', name: 'Window Air Conditioner', category: 'appliances_large', lowFMV: 25, highFMV: 75, source: 'goodwill', keywords: ['ac unit'] },
  { id: 'la-008', name: 'Dehumidifier', category: 'appliances_large', lowFMV: 15, highFMV: 50, source: 'goodwill' },

  // ── Kitchen & Dining ────────────────────────────────────
  { id: 'ki-001', name: 'Pots & Pans Set', category: 'kitchen', lowFMV: 15, highFMV: 60, source: 'salvation_army', keywords: ['cookware', 'cookware set'] },
  { id: 'ki-002', name: 'Skillet / Frying Pan', category: 'kitchen', lowFMV: 3, highFMV: 12, source: 'goodwill', keywords: ['pan', 'frying pan', 'cast iron'] },
  { id: 'ki-003', name: 'Dish Set', category: 'kitchen', lowFMV: 10, highFMV: 40, source: 'salvation_army', keywords: ['dinnerware', 'plates', 'china'] },
  { id: 'ki-004', name: 'Flatware Set', category: 'kitchen', lowFMV: 5, highFMV: 25, source: 'salvation_army', keywords: ['silverware', 'utensils'] },
  { id: 'ki-005', name: 'Glassware Set', category: 'kitchen', lowFMV: 3, highFMV: 15, source: 'salvation_army', keywords: ['glasses', 'cups'] },
  { id: 'ki-006', name: 'Bakeware Set', category: 'kitchen', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['baking pans', 'cookie sheets'] },
  { id: 'ki-007', name: 'Knife Set', category: 'kitchen', lowFMV: 5, highFMV: 25, source: 'goodwill', keywords: ['kitchen knives'] },
  { id: 'ki-008', name: 'Mixing Bowls', category: 'kitchen', lowFMV: 3, highFMV: 10, source: 'goodwill' },
  { id: 'ki-009', name: 'Serving Platter', category: 'kitchen', lowFMV: 3, highFMV: 12, source: 'goodwill' },

  // ── Sports & Recreation ─────────────────────────────────
  { id: 'sr-001', name: 'Bicycle (adult)', category: 'sports_recreation', lowFMV: 20, highFMV: 100, source: 'salvation_army', keywords: ['bike'] },
  { id: 'sr-002', name: 'Bicycle (child)', category: 'sports_recreation', lowFMV: 10, highFMV: 40, source: 'salvation_army', keywords: ['kids bike'] },
  { id: 'sr-003', name: 'Golf Clubs (set)', category: 'sports_recreation', lowFMV: 25, highFMV: 125, source: 'salvation_army', keywords: ['golf set', 'golf bag'] },
  { id: 'sr-004', name: 'Golf Club (single)', category: 'sports_recreation', lowFMV: 3, highFMV: 15, source: 'goodwill' },
  { id: 'sr-005', name: 'Skis (pair)', category: 'sports_recreation', lowFMV: 15, highFMV: 75, source: 'salvation_army', keywords: ['skiing'] },
  { id: 'sr-006', name: 'Ski Boots', category: 'sports_recreation', lowFMV: 10, highFMV: 40, source: 'salvation_army' },
  { id: 'sr-007', name: 'Snowboard', category: 'sports_recreation', lowFMV: 15, highFMV: 60, source: 'goodwill' },
  { id: 'sr-008', name: 'Tennis Racket', category: 'sports_recreation', lowFMV: 3, highFMV: 15, source: 'salvation_army', keywords: ['racquet'] },
  { id: 'sr-009', name: 'Exercise Equipment (home gym)', category: 'sports_recreation', lowFMV: 25, highFMV: 150, source: 'salvation_army', keywords: ['weights', 'bench press', 'home gym'] },
  { id: 'sr-010', name: 'Treadmill', category: 'sports_recreation', lowFMV: 50, highFMV: 200, source: 'salvation_army' },
  { id: 'sr-011', name: 'Stationary Bike', category: 'sports_recreation', lowFMV: 30, highFMV: 125, source: 'goodwill', keywords: ['exercise bike', 'spin bike'] },
  { id: 'sr-012', name: 'Elliptical', category: 'sports_recreation', lowFMV: 40, highFMV: 175, source: 'goodwill' },
  { id: 'sr-013', name: 'Yoga Mat', category: 'sports_recreation', lowFMV: 2, highFMV: 8, source: 'goodwill' },
  { id: 'sr-014', name: 'Camping Tent', category: 'sports_recreation', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['tent'] },
  { id: 'sr-015', name: 'Sleeping Bag', category: 'sports_recreation', lowFMV: 5, highFMV: 25, source: 'salvation_army' },
  { id: 'sr-016', name: 'Fishing Rod', category: 'sports_recreation', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['fishing pole'] },
  { id: 'sr-017', name: 'Baseball Glove', category: 'sports_recreation', lowFMV: 3, highFMV: 15, source: 'goodwill', keywords: ['mitt'] },

  // ── Toys & Games ────────────────────────────────────────
  { id: 'tg-001', name: 'Board Game', category: 'toys_games', lowFMV: 2, highFMV: 8, source: 'salvation_army' },
  { id: 'tg-002', name: 'Puzzle', category: 'toys_games', lowFMV: 1, highFMV: 4, source: 'goodwill', keywords: ['jigsaw'] },
  { id: 'tg-003', name: 'Stuffed Animal', category: 'toys_games', lowFMV: 1, highFMV: 5, source: 'salvation_army', keywords: ['plush', 'teddy bear'] },
  { id: 'tg-004', name: 'Action Figure', category: 'toys_games', lowFMV: 1, highFMV: 6, source: 'goodwill' },
  { id: 'tg-005', name: 'Doll', category: 'toys_games', lowFMV: 2, highFMV: 10, source: 'salvation_army' },
  { id: 'tg-006', name: 'Building Set (e.g., LEGO)', category: 'toys_games', lowFMV: 5, highFMV: 30, source: 'goodwill', keywords: ['lego', 'blocks', 'building blocks'] },
  { id: 'tg-007', name: 'Toy Vehicle', category: 'toys_games', lowFMV: 2, highFMV: 8, source: 'goodwill', keywords: ['toy car', 'toy truck'] },
  { id: 'tg-008', name: 'Play Kitchen / Playset', category: 'toys_games', lowFMV: 10, highFMV: 40, source: 'salvation_army', keywords: ['playset'] },
  { id: 'tg-009', name: 'Stroller', category: 'toys_games', lowFMV: 15, highFMV: 60, source: 'salvation_army', keywords: ['baby stroller'] },
  { id: 'tg-010', name: 'Car Seat', category: 'toys_games', lowFMV: 15, highFMV: 50, source: 'goodwill', keywords: ['infant car seat', 'booster seat'] },
  { id: 'tg-011', name: 'High Chair', category: 'toys_games', lowFMV: 10, highFMV: 35, source: 'salvation_army' },
  { id: 'tg-012', name: 'Video Game (cartridge/disc)', category: 'toys_games', lowFMV: 2, highFMV: 15, source: 'goodwill', keywords: ['game disc', 'game cartridge'] },

  // ── Books & Media ───────────────────────────────────────
  { id: 'bm-001', name: 'Hardcover Book', category: 'books_media', lowFMV: 1, highFMV: 5, source: 'salvation_army', keywords: ['book'] },
  { id: 'bm-002', name: 'Paperback Book', category: 'books_media', lowFMV: 0.5, highFMV: 2, source: 'salvation_army', keywords: ['book'] },
  { id: 'bm-003', name: 'Textbook', category: 'books_media', lowFMV: 3, highFMV: 15, source: 'goodwill', keywords: ['college textbook'] },
  { id: 'bm-004', name: 'CD', category: 'books_media', lowFMV: 0.5, highFMV: 3, source: 'salvation_army', keywords: ['compact disc', 'music cd'] },
  { id: 'bm-005', name: 'DVD', category: 'books_media', lowFMV: 1, highFMV: 4, source: 'salvation_army', keywords: ['movie'] },
  { id: 'bm-006', name: 'Blu-ray Disc', category: 'books_media', lowFMV: 2, highFMV: 6, source: 'goodwill', keywords: ['bluray'] },
  { id: 'bm-007', name: 'Vinyl Record', category: 'books_media', lowFMV: 1, highFMV: 8, source: 'goodwill', keywords: ['lp', 'album', 'record'] },
  { id: 'bm-008', name: "Children's Book", category: 'books_media', lowFMV: 0.5, highFMV: 3, source: 'goodwill', keywords: ['kids book', 'picture book'] },

  // ── Household Items ─────────────────────────────────────
  { id: 'hh-001', name: 'Bedding Set (comforter + sheets)', category: 'household', lowFMV: 10, highFMV: 40, source: 'salvation_army', keywords: ['comforter', 'sheets', 'bedspread'] },
  { id: 'hh-002', name: 'Blanket', category: 'household', lowFMV: 3, highFMV: 12, source: 'salvation_army', keywords: ['throw', 'quilt'] },
  { id: 'hh-003', name: 'Towel Set', category: 'household', lowFMV: 3, highFMV: 10, source: 'salvation_army', keywords: ['bath towels'] },
  { id: 'hh-004', name: 'Curtains / Drapes (pair)', category: 'household', lowFMV: 4, highFMV: 18, source: 'salvation_army', keywords: ['window curtains'] },
  { id: 'hh-005', name: 'Area Rug', category: 'household', lowFMV: 8, highFMV: 50, source: 'salvation_army', keywords: ['rug', 'carpet'] },
  { id: 'hh-006', name: 'Lamp (table)', category: 'household', lowFMV: 5, highFMV: 20, source: 'salvation_army', keywords: ['table lamp', 'desk lamp'] },
  { id: 'hh-007', name: 'Lamp (floor)', category: 'household', lowFMV: 8, highFMV: 35, source: 'salvation_army', keywords: ['floor lamp', 'standing lamp'] },
  { id: 'hh-008', name: 'Picture Frame', category: 'household', lowFMV: 2, highFMV: 8, source: 'goodwill', keywords: ['frame'] },
  { id: 'hh-009', name: 'Wall Art / Print', category: 'household', lowFMV: 5, highFMV: 25, source: 'goodwill', keywords: ['painting', 'poster', 'wall decor'] },
  { id: 'hh-010', name: 'Mirror', category: 'household', lowFMV: 5, highFMV: 25, source: 'salvation_army' },
  { id: 'hh-011', name: 'Vase', category: 'household', lowFMV: 2, highFMV: 10, source: 'goodwill' },
  { id: 'hh-012', name: 'Clock (wall)', category: 'household', lowFMV: 3, highFMV: 12, source: 'goodwill', keywords: ['wall clock'] },
  { id: 'hh-013', name: 'Pillow (decorative)', category: 'household', lowFMV: 2, highFMV: 6, source: 'goodwill', keywords: ['throw pillow'] },
  { id: 'hh-014', name: 'Storage Basket / Bin', category: 'household', lowFMV: 2, highFMV: 6, source: 'goodwill', keywords: ['basket', 'bin', 'organizer'] },

  // ── Miscellaneous ───────────────────────────────────────
  { id: 'mi-001', name: 'Luggage / Suitcase', category: 'miscellaneous', lowFMV: 8, highFMV: 40, source: 'salvation_army', keywords: ['suitcase', 'travel bag'] },
  { id: 'mi-002', name: 'Backpack', category: 'miscellaneous', lowFMV: 3, highFMV: 15, source: 'goodwill' },
  { id: 'mi-003', name: 'Briefcase', category: 'miscellaneous', lowFMV: 5, highFMV: 20, source: 'salvation_army' },
  { id: 'mi-004', name: 'Musical Instrument (guitar)', category: 'miscellaneous', lowFMV: 20, highFMV: 100, source: 'salvation_army', keywords: ['guitar', 'acoustic guitar', 'electric guitar'] },
  { id: 'mi-005', name: 'Musical Instrument (keyboard/piano)', category: 'miscellaneous', lowFMV: 30, highFMV: 150, source: 'salvation_army', keywords: ['keyboard', 'piano', 'electric piano'] },
  { id: 'mi-006', name: 'Musical Instrument (other)', category: 'miscellaneous', lowFMV: 10, highFMV: 75, source: 'salvation_army', keywords: ['violin', 'drums', 'trumpet', 'saxophone', 'flute'] },
  { id: 'mi-007', name: 'Hand Tools (set)', category: 'miscellaneous', lowFMV: 5, highFMV: 25, source: 'salvation_army', keywords: ['toolset', 'wrench', 'screwdriver'] },
  { id: 'mi-008', name: 'Power Tool', category: 'miscellaneous', lowFMV: 10, highFMV: 50, source: 'salvation_army', keywords: ['drill', 'saw', 'sander'] },
  { id: 'mi-009', name: 'Lawn Mower', category: 'miscellaneous', lowFMV: 25, highFMV: 100, source: 'salvation_army', keywords: ['mower'] },
  { id: 'mi-010', name: 'Snow Blower', category: 'miscellaneous', lowFMV: 30, highFMV: 125, source: 'goodwill', keywords: ['snowblower'] },
  { id: 'mi-011', name: 'Garden Tools', category: 'miscellaneous', lowFMV: 3, highFMV: 15, source: 'goodwill', keywords: ['shovel', 'rake', 'hoe'] },
  { id: 'mi-012', name: 'Pet Crate / Carrier', category: 'miscellaneous', lowFMV: 5, highFMV: 20, source: 'goodwill', keywords: ['dog crate', 'pet carrier'] },
  { id: 'mi-013', name: 'Jewelry (costume)', category: 'miscellaneous', lowFMV: 2, highFMV: 10, source: 'goodwill', keywords: ['necklace', 'bracelet', 'earrings'] },
  { id: 'mi-014', name: 'Watch', category: 'miscellaneous', lowFMV: 5, highFMV: 30, source: 'goodwill', keywords: ['wristwatch'] },
  { id: 'mi-015', name: 'Bicycle Helmet', category: 'miscellaneous', lowFMV: 3, highFMV: 10, source: 'goodwill', keywords: ['helmet'] },
  { id: 'mi-016', name: 'Baby Monitor', category: 'miscellaneous', lowFMV: 5, highFMV: 20, source: 'goodwill' },
  { id: 'mi-017', name: 'Grill (outdoor)', category: 'miscellaneous', lowFMV: 15, highFMV: 75, source: 'salvation_army', keywords: ['bbq', 'barbecue', 'charcoal grill', 'gas grill'] },
];

// ─── Depreciation Schedules ─────────────────────────────────
// Rates = cumulative fraction LOST. FMV = originalPrice * (1 - rate)

const DEPRECIATION_DISCLAIMER =
  'Estimate based on typical resale depreciation. Not an IRS-published value. Verify against comparable sales.';

export const DEPRECIATION_SCHEDULES: DepreciationSchedule[] = [
  {
    category: 'electronics',
    rates: [0.43, 0.50, 0.57, 0.70, 0.80],
    floorRate: 0.90,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'furniture',
    rates: [0.07, 0.14, 0.20, 0.27, 0.35],
    floorRate: 0.50,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'clothing_mens',
    rates: [0.50, 0.65, 0.75, 0.85, 0.90],
    floorRate: 0.95,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'clothing_womens',
    rates: [0.50, 0.65, 0.75, 0.85, 0.90],
    floorRate: 0.95,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'clothing_childrens',
    rates: [0.50, 0.65, 0.75, 0.85, 0.90],
    floorRate: 0.95,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'appliances_small',
    rates: [0.15, 0.28, 0.40, 0.50, 0.60],
    floorRate: 0.75,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'appliances_large',
    rates: [0.15, 0.28, 0.40, 0.50, 0.60],
    floorRate: 0.75,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
  {
    category: 'general',
    rates: [0.30, 0.45, 0.60, 0.72, 0.80],
    floorRate: 0.90,
    disclaimer: DEPRECIATION_DISCLAIMER,
  },
];

/** Look up the depreciation schedule for a category, falling back to 'general'. */
export function getDepreciationSchedule(category: DonationCategory | 'general'): DepreciationSchedule {
  return DEPRECIATION_SCHEDULES.find((s) => s.category === category)
    ?? DEPRECIATION_SCHEDULES.find((s) => s.category === 'general')!;
}
