/**
 * Tests for competitor return parser — extracts personal info, dependents,
 * and financials from completed 1040 PDFs generated by competitor tax software.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { FilingStatus } from '@telostax/engine';

// ─── Mock pdfjs-dist ────────────────────────────────

vi.mock('pdfjs-dist', () => ({
  GlobalWorkerOptions: { workerSrc: '' },
  getDocument: vi.fn(),
}));

import * as pdfjsLib from 'pdfjs-dist';
import {
  parseCompetitorReturn,
  sanitizeSsnToLastFour,
  type CompetitorExtractResult,
} from '../services/competitorReturnParser';
import { detectProvider, getProvider } from '../data/competitorProviders';
import { parseDollarValue, findLineValue, type TextBlock } from '../services/pdfTextUtils';

// ─── Helpers ────────────────────────────────────────

function makeFile(
  content: ArrayBuffer = new ArrayBuffer(100),
  name = 'return.pdf',
  size = 100,
): File {
  const blob = new Blob([content], { type: 'application/pdf' });
  return new File([blob], name, { type: 'application/pdf' });
}

interface MockTextItem {
  str: string;
  transform: number[]; // [scaleX, skewX, skewY, scaleY, translateX, translateY]
}

function makeTextItem(text: string, x: number, y: number): MockTextItem {
  return { str: text, transform: [1, 0, 0, 1, x, y] };
}

function makeMockPage(
  textItems: MockTextItem[],
  annotations: Array<Record<string, unknown>> = [],
) {
  return {
    getTextContent: vi.fn().mockResolvedValue({ items: textItems }),
    getAnnotations: vi.fn().mockResolvedValue(annotations),
    getViewport: vi.fn().mockReturnValue({ height: 792 }), // Standard US Letter height
  };
}

function setupMockPdf(
  pages: ReturnType<typeof makeMockPage>[],
) {
  const mockDoc = {
    numPages: pages.length,
    getPage: vi.fn().mockImplementation((num: number) => Promise.resolve(pages[num - 1])),
  };

  vi.mocked(pdfjsLib.getDocument).mockReturnValue({
    promise: Promise.resolve(mockDoc),
  } as unknown as ReturnType<typeof pdfjsLib.getDocument>);

  return mockDoc;
}

// Standard 1040 page 1 text items (minimal — just enough for find1040Pages)
function make1040Page1Items(extras: MockTextItem[] = []): MockTextItem[] {
  return [
    makeTextItem('Department of the Treasury', 50, 750),
    makeTextItem('Internal Revenue Service', 50, 740),
    makeTextItem('Form 1040', 250, 750),
    makeTextItem('U.S. Individual Income Tax Return', 350, 750),
    makeTextItem('2024', 500, 750),
    makeTextItem('Your first name and middle initial', 30, 680),
    makeTextItem('Last name', 300, 680),
    ...extras,
  ];
}

function make1040Page2Items(extras: MockTextItem[] = []): MockTextItem[] {
  return [
    makeTextItem('Form 1040 (2024)', 50, 750),
    makeTextItem('Page 2', 500, 750),
    ...extras,
  ];
}

beforeEach(() => {
  vi.clearAllMocks();
});

// ─── Provider Detection Tests ───────────────────────

describe('competitorProviders', () => {
  describe('detectProvider', () => {
    it('should detect TurboTax from PDF text', () => {
      expect(detectProvider('Prepared by TurboTax for tax year 2024')).toBe('turbotax');
    });

    it('should detect TurboTax from Intuit reference', () => {
      expect(detectProvider('Intuit Tax Software — Form 1040')).toBe('turbotax');
    });

    it('should detect H&R Block', () => {
      expect(detectProvider('This return was prepared using H&R Block software')).toBe('hrblock');
    });

    it('should detect H&R Block case-insensitively', () => {
      expect(detectProvider('h&r block online 2024')).toBe('hrblock');
    });

    it('should detect TaxAct', () => {
      expect(detectProvider('TaxAct Online 2024 Federal Return')).toBe('taxact');
    });

    it('should detect FreeTaxUSA', () => {
      expect(detectProvider('Filed with FreeTaxUSA for 2024')).toBe('freetaxusa');
    });

    it('should detect FreeTaxUSA from TaxHawk reference', () => {
      expect(detectProvider('TaxHawk, Inc. FreeTaxUSA')).toBe('freetaxusa');
    });

    it('should detect Cash App Taxes', () => {
      expect(detectProvider('Cash App Taxes 2024 Federal Return')).toBe('cashapp');
    });

    it('should detect Cash App from Credit Karma reference', () => {
      expect(detectProvider('Prepared by Credit Karma Tax')).toBe('cashapp');
    });

    it('should return undefined for unknown provider', () => {
      expect(detectProvider('IRS Form 1040 U.S. Individual Income Tax Return 2024')).toBeUndefined();
    });
  });

  describe('getProvider', () => {
    it('should return provider by ID', () => {
      expect(getProvider('turbotax').name).toBe('TurboTax');
    });

    it('should fallback to Other for unknown ID', () => {
      expect(getProvider('nonexistent').id).toBe('other');
    });
  });
});

// ─── SSN Sanitization ───────────────────────────────

describe('sanitizeSsnToLastFour', () => {
  it('should extract last 4 from full SSN with dashes', () => {
    expect(sanitizeSsnToLastFour('123-45-6789')).toBe('6789');
  });

  it('should extract last 4 from full SSN without dashes', () => {
    expect(sanitizeSsnToLastFour('123456789')).toBe('6789');
  });

  it('should extract last 4 from SSN with spaces', () => {
    expect(sanitizeSsnToLastFour('123 45 6789')).toBe('6789');
  });

  it('should return last 4 from exactly 4 digits', () => {
    expect(sanitizeSsnToLastFour('6789')).toBe('6789');
  });

  it('should return undefined for fewer than 4 digits', () => {
    expect(sanitizeSsnToLastFour('12')).toBeUndefined();
  });

  it('should return undefined for empty string', () => {
    expect(sanitizeSsnToLastFour('')).toBeUndefined();
  });
});

// ─── parseDollarValue Tests ──────────────────────────

describe('parseDollarValue', () => {
  it('should parse a simple dollar amount', () => {
    expect(parseDollarValue('$1,234.56')).toBe(1234.56);
  });

  it('should parse amount without dollar sign', () => {
    expect(parseDollarValue('1234.56')).toBe(1234.56);
  });

  it('should parse whole number', () => {
    expect(parseDollarValue('50000')).toBe(50000);
  });

  it('should handle accounting-format negatives (500)', () => {
    expect(parseDollarValue('(500)')).toBe(-500);
  });

  it('should handle accounting-format with dollar sign ($1,234.56)', () => {
    expect(parseDollarValue('($1,234.56)')).toBe(-1234.56);
  });

  it('should handle accounting-format large values', () => {
    expect(parseDollarValue('(12,345)')).toBe(-12345);
  });

  it('should handle standard negative with minus sign', () => {
    expect(parseDollarValue('-500')).toBe(-500);
  });

  it('should handle negative with dollar sign', () => {
    expect(parseDollarValue('-$1,234.56')).toBe(-1234.56);
  });

  it('should return null for empty string', () => {
    expect(parseDollarValue('')).toBeNull();
  });

  it('should return null for whitespace only', () => {
    expect(parseDollarValue('   ')).toBeNull();
  });

  it('should return null for non-numeric string', () => {
    expect(parseDollarValue('abc')).toBeNull();
  });

  it('should round to cents', () => {
    expect(parseDollarValue('1.999')).toBe(2);
  });

  it('should handle dollar sign and commas with spaces', () => {
    expect(parseDollarValue('$ 1, 234')).toBe(1234);
  });
});

// ─── findLineValue Tests ────────────────────────────

describe('findLineValue', () => {
  it('should find a value to the right of a label keyword', () => {
    const blocks: TextBlock[] = [
      { text: 'Total income', x: 50, y: 500, page: 1 },
      { text: '85,000', x: 450, y: 500, page: 1 },
    ];
    expect(findLineValue(blocks, ['total income'])).toBe(85000);
  });

  it('should pick the rightmost value on the same line', () => {
    const blocks: TextBlock[] = [
      { text: 'Line 9', x: 30, y: 500, page: 1 },
      { text: 'Total income', x: 50, y: 500, page: 1 },
      { text: '9', x: 350, y: 500, page: 1 },       // line number
      { text: '85,000', x: 500, y: 500, page: 1 },   // actual amount (rightmost)
    ];
    expect(findLineValue(blocks, ['total income'])).toBe(85000);
  });

  it('should return 0 when no keyword matches', () => {
    const blocks: TextBlock[] = [
      { text: 'Other label', x: 50, y: 500, page: 1 },
      { text: '100', x: 450, y: 500, page: 1 },
    ];
    expect(findLineValue(blocks, ['total income'])).toBe(0);
  });

  it('should handle accounting-format negatives in text blocks', () => {
    const blocks: TextBlock[] = [
      { text: 'Capital loss', x: 50, y: 500, page: 1 },
      { text: '(3,500)', x: 450, y: 500, page: 1 },
    ];
    expect(findLineValue(blocks, ['capital loss'])).toBe(-3500);
  });

  it('should handle accounting-format with dollar sign', () => {
    const blocks: TextBlock[] = [
      { text: 'Net loss', x: 50, y: 500, page: 1 },
      { text: '($1,200)', x: 450, y: 500, page: 1 },
    ];
    expect(findLineValue(blocks, ['net loss'])).toBe(-1200);
  });

  it('should tolerate ±30px vertical variance', () => {
    const blocks: TextBlock[] = [
      { text: 'Wages', x: 50, y: 500, page: 1 },
      { text: '75,000', x: 450, y: 520, page: 1 }, // 20px off — within tolerance
    ];
    expect(findLineValue(blocks, ['wages'])).toBe(75000);
  });
});

// ─── AcroForm Extraction Tests ──────────────────────

describe('AcroForm extraction', () => {
  it('should extract personal info from AcroForm annotations', async () => {
    const P1 = 'topmostSubform[0].Page1[0]';
    const ADDR = `${P1}.Address_ReadOrder[0]`;
    const CB = `${P1}.Checkbox_ReadOrder[0]`;

    const annotations = [
      { subtype: 'Widget', fieldName: `${P1}.f1_14[0]`, fieldValue: 'Jane' },
      { subtype: 'Widget', fieldName: `${P1}.f1_15[0]`, fieldValue: 'Doe' },
      { subtype: 'Widget', fieldName: `${ADDR}.f1_20[0]`, fieldValue: '789 Elm St' },
      { subtype: 'Widget', fieldName: `${ADDR}.f1_22[0]`, fieldValue: 'Austin' },
      { subtype: 'Widget', fieldName: `${ADDR}.f1_23[0]`, fieldValue: 'TX' },
      { subtype: 'Widget', fieldName: `${ADDR}.f1_24[0]`, fieldValue: '73301' },
      { subtype: 'Widget', fieldName: `${CB}.c1_8[1]`, fieldValue: '1' }, // MFJ
    ];

    const page1 = makeMockPage(make1040Page1Items([
      ...Array.from({ length: 15 }, (_, i) =>
        makeTextItem(`Content ${i}`, 50, 600 - i * 20),
      ),
    ]), annotations);
    const page2 = makeMockPage(make1040Page2Items());
    setupMockPdf([page1, page2]);

    const result = await parseCompetitorReturn(makeFile());
    // AcroForm values should be high confidence
    expect(result.personalInfo.firstName.value).toBe('Jane');
    expect(result.personalInfo.firstName.confidence).toBe('high');
    expect(result.personalInfo.lastName.value).toBe('Doe');
    expect(result.personalInfo.lastName.confidence).toBe('high');
    expect(result.personalInfo.addressStreet.value).toBe('789 Elm St');
    expect(result.personalInfo.addressCity.value).toBe('Austin');
    expect(result.personalInfo.addressState.value).toBe('TX');
    expect(result.personalInfo.addressZip.value).toBe('73301');
    expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.MarriedFilingJointly);
    expect(result.personalInfo.filingStatus.confidence).toBe('high');
  });

  it('should NOT extract SSN fields from AcroForm', async () => {
    const P1 = 'topmostSubform[0].Page1[0]';
    const annotations = [
      { subtype: 'Widget', fieldName: `${P1}.f1_14[0]`, fieldValue: 'Test' },
      { subtype: 'Widget', fieldName: `${P1}.f1_15[0]`, fieldValue: 'User' },
      { subtype: 'Widget', fieldName: `${P1}.f1_16[0]`, fieldValue: '123-45-6789' }, // SSN field
      { subtype: 'Widget', fieldName: `${P1}.f1_19[0]`, fieldValue: '987-65-4321' }, // Spouse SSN
    ];

    const page1 = makeMockPage(make1040Page1Items([
      ...Array.from({ length: 15 }, (_, i) =>
        makeTextItem(`Content ${i}`, 50, 600 - i * 20),
      ),
    ]), annotations);
    const page2 = makeMockPage(make1040Page2Items());
    setupMockPdf([page1, page2]);

    const result = await parseCompetitorReturn(makeFile());
    // SSN should never appear in results
    const resultJson = JSON.stringify(result);
    expect(resultJson).not.toContain('123-45-6789');
    expect(resultJson).not.toContain('123456789');
    expect(resultJson).not.toContain('987-65-4321');
    expect(resultJson).not.toContain('987654321');
  });

  it('should extract dependents from AcroForm annotations', async () => {
    const P1 = 'topmostSubform[0].Page1[0]';
    const DEP = `${P1}.Table_Dependents[0]`;
    const annotations = [
      { subtype: 'Widget', fieldName: `${P1}.f1_14[0]`, fieldValue: 'Parent' },
      { subtype: 'Widget', fieldName: `${P1}.f1_15[0]`, fieldValue: 'Smith' },
      // Dependent 1
      { subtype: 'Widget', fieldName: `${DEP}.Row1[0].f1_31[0]`, fieldValue: 'Alice' },
      { subtype: 'Widget', fieldName: `${DEP}.Row2[0].f1_35[0]`, fieldValue: 'Smith' },
      { subtype: 'Widget', fieldName: `${DEP}.Row3[0].f1_39[0]`, fieldValue: '111-22-3333' },
      { subtype: 'Widget', fieldName: `${DEP}.Row4[0].f1_43[0]`, fieldValue: 'Daughter' },
    ];

    const page1 = makeMockPage(make1040Page1Items([
      ...Array.from({ length: 15 }, (_, i) =>
        makeTextItem(`Content ${i}`, 50, 600 - i * 20),
      ),
    ]), annotations);
    const page2 = makeMockPage(make1040Page2Items());
    setupMockPdf([page1, page2]);

    const result = await parseCompetitorReturn(makeFile());
    expect(result.dependents).toHaveLength(1);
    expect(result.dependents[0].firstName).toBe('Alice');
    expect(result.dependents[0].lastName).toBe('Smith');
    expect(result.dependents[0].ssnLastFour).toBe('3333'); // Only last 4
    expect(result.dependents[0].relationship).toBe('Daughter');
  });
});

// ─── Main Parser Tests ──────────────────────────────

describe('parseCompetitorReturn', () => {
  describe('file validation', () => {
    it('should reject files over 25 MB', async () => {
      const bigFile = new File(
        [new ArrayBuffer(26 * 1024 * 1024)],
        'big.pdf',
        { type: 'application/pdf' },
      );
      // Override size getter since File might not respect ArrayBuffer size in tests
      Object.defineProperty(bigFile, 'size', { value: 26 * 1024 * 1024 });

      await expect(parseCompetitorReturn(bigFile)).rejects.toThrow('too large');
    });

    it('should reject password-protected PDFs', async () => {
      const err = new Error('Need password');
      (err as unknown as { name: string }).name = 'PasswordException';
      vi.mocked(pdfjsLib.getDocument).mockReturnValue({
        promise: Promise.reject(err),
      } as unknown as ReturnType<typeof pdfjsLib.getDocument>);

      await expect(parseCompetitorReturn(makeFile())).rejects.toThrow('password-protected');
    });

    it('should reject non-PDF files', async () => {
      vi.mocked(pdfjsLib.getDocument).mockReturnValue({
        promise: Promise.reject(new Error('Invalid PDF')),
      } as unknown as ReturnType<typeof pdfjsLib.getDocument>);

      await expect(parseCompetitorReturn(makeFile())).rejects.toThrow('valid PDF');
    });
  });

  describe('1040 page detection', () => {
    it('should reject PDF without Form 1040 content', async () => {
      const page = makeMockPage([
        makeTextItem('Some random document', 50, 700),
        makeTextItem('Not a tax return', 50, 680),
        // Need enough blocks to pass scanned check
        ...Array.from({ length: 12 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 650 - i * 20),
        ),
      ]);
      setupMockPdf([page, page, page]);

      await expect(parseCompetitorReturn(makeFile())).rejects.toThrow('Could not find Form 1040');
    });

    it('should detect scanned/image-based PDFs (few text blocks)', async () => {
      // Page with "Form 1040" text (so find1040Pages succeeds) but very few blocks
      const page = makeMockPage([
        makeTextItem('Form 1040', 250, 750),
        makeTextItem('U.S. Individual Income Tax Return', 350, 750),
        // Only 2 blocks — clearly image-based
      ]);
      setupMockPdf([page]);

      await expect(parseCompetitorReturn(makeFile())).rejects.toThrow('scanned or image-based');
    });

    it('should reject Form 1040-X (amended returns)', async () => {
      const page = makeMockPage([
        makeTextItem('Form 1040-X', 250, 750),
        makeTextItem('U.S. Individual Income Tax Return', 350, 750),
        makeTextItem('Amended U.S. Individual Income Tax Return', 200, 730),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Content ${i}`, 50, 650 - i * 20),
        ),
      ]);
      setupMockPdf([page]);

      // find1040Pages will match "form 1040" (substring of "form 1040-x")
      // but the parser should detect "1040-x" and reject
      await expect(parseCompetitorReturn(makeFile())).rejects.toThrow('amended return');
    });
  });

  describe('text-based personal info extraction', () => {
    it('should extract name from labeled fields', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('John', 200, 680),  // next to "Your first name" label
        makeTextItem('Smith', 400, 680), // next to "Last name" label
        makeTextItem('123 Main St', 50, 640),
        makeTextItem('Springfield', 50, 620),
        makeTextItem('IL', 200, 620),
        makeTextItem('62701', 250, 620),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 500 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.firstName.value).toBe('John');
      expect(result.personalInfo.lastName.value).toBe('Smith');
    });

    it('should extract address via ZIP anchor pattern', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('456 Oak Avenue', 50, 640),
        makeTextItem('Portland', 50, 620),
        makeTextItem('OR', 200, 620),
        makeTextItem('97201', 250, 620),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 500 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.addressZip.value).toBe('97201');
      expect(result.personalInfo.addressState.value).toBe('OR');
    });

    it('should detect tax year from PDF header', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Content ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.detectedTaxYear).toBe(2024);
    });
  });

  describe('filing status detection', () => {
    it('should detect Married Filing Jointly', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('Married filing jointly', 100, 710),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.MarriedFilingJointly);
    });

    it('should detect Head of Household', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('Head of household', 100, 710),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.HeadOfHousehold);
    });

    it('should detect Married Filing Separately', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('Married filing separately', 100, 710),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.MarriedFilingSeparately);
    });

    it('should detect MFJ via checkmark when all filing status labels are present', async () => {
      // Simulates a real flattened 1040 where all 5 labels are printed and
      // only the checked status has a ✔ to its left. Single and MFJ are
      // stacked vertically at the same x, so the checkmark proximity must
      // pick the closest label, not the first in iteration order.
      const page1 = makeMockPage(make1040Page1Items([
        // All 5 filing status labels (PDF y coords; TextBlock y = 792 - pdfY)
        makeTextItem('Single', 80, 720),                           // TextBlock y=72
        makeTextItem('Married filing jointly', 80, 708),           // TextBlock y=84
        makeTextItem('Married filing separately', 80, 696),        // TextBlock y=96
        makeTextItem('Head of household', 350, 720),               // TextBlock y=72
        makeTextItem('Qualifying surviving spouse', 350, 708),     // TextBlock y=84
        // Checkmark next to MFJ (same y as MFJ label, to its left)
        makeTextItem('✔', 65, 708),                                // TextBlock y=84
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.MarriedFilingJointly);
    });

    it('should detect Single via checkmark when all filing status labels are present', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('Single', 80, 720),
        makeTextItem('Married filing jointly', 80, 708),
        makeTextItem('Married filing separately', 80, 696),
        makeTextItem('Head of household', 350, 720),
        makeTextItem('Qualifying surviving spouse', 350, 708),
        makeTextItem('✔', 65, 720), // checkmark next to Single
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.personalInfo.filingStatus.value).toBe(FilingStatus.Single);
    });
  });

  describe('provider detection', () => {
    it('should detect TurboTax from PDF text', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('Prepared by TurboTax', 400, 780),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.detectedProvider).toBe('turbotax');
    });

    it('should return undefined for unrecognized provider', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.detectedProvider).toBeUndefined();
    });
  });

  describe('"DO NOT FILE" watermark detection', () => {
    it('should warn on "DO NOT FILE" watermark', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('DO NOT FILE', 300, 500),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 450 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.warnings.some(w => w.includes('DO NOT FILE'))).toBe(true);
    });
  });

  describe('multi-page PDF handling', () => {
    it('should find 1040 pages in a multi-page competitor bundle', async () => {
      // Page 1: cover page (not 1040)
      const coverPage = makeMockPage([
        makeTextItem('Tax Return Summary', 200, 700),
        makeTextItem('Prepared for John Smith', 200, 680),
        ...Array.from({ length: 12 }, (_, i) =>
          makeTextItem(`Summary line ${i}`, 50, 600 - i * 20),
        ),
      ]);
      // Page 2: actual 1040 page 1
      const actualPage1 = makeMockPage(make1040Page1Items([
        makeTextItem('John', 200, 680),
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      // Page 3: 1040 page 2
      const actualPage2 = makeMockPage(make1040Page2Items([
        makeTextItem('$50,000', 400, 600),
      ]));
      // Page 4: state return
      const statePage = makeMockPage([
        makeTextItem('State of Illinois Tax Return', 200, 700),
      ]);

      setupMockPdf([coverPage, actualPage1, actualPage2, statePage]);

      const result = await parseCompetitorReturn(makeFile());
      // Should succeed — found the 1040 on pages 2-3
      // detectTaxYear now scans multiple pages, so it finds "2024" on the
      // actual 1040 page even though the cover page has no year.
      expect(result.detectedTaxYear).toBe(2024);
    });
  });

  describe('financial data extraction', () => {
    it('should extract financial totals from text when no AcroForm', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        makeTextItem('1a', 30, 500),
        makeTextItem('Wages, salaries, tips', 50, 500),
        makeTextItem('75,000', 500, 500),
        makeTextItem('Total income', 50, 460),
        makeTextItem('line 9', 180, 460),
        makeTextItem('85,000', 500, 460),
        makeTextItem('Adjusted gross income', 50, 440),
        makeTextItem('line 11', 200, 440),
        makeTextItem('80,000', 500, 440),
        ...Array.from({ length: 5 }, (_, i) =>
          makeTextItem(`Extra ${i}`, 50, 400 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items([
        makeTextItem('Taxable income', 50, 700),
        makeTextItem('line 15', 180, 700),
        makeTextItem('65,000', 500, 700),
        makeTextItem('Total tax', 50, 650),
        makeTextItem('line 24', 150, 650),
        makeTextItem('10,500', 500, 650),
      ]));

      setupMockPdf([page1, page2]);
      const result = await parseCompetitorReturn(makeFile());

      // Financial data should be extracted
      expect(result.financials).toBeDefined();
      expect(result.warnings.some(w => w.includes('text extraction'))).toBe(true);
    });
  });

  describe('graceful degradation', () => {
    it('should return empty/default fields when info is missing', async () => {
      // Minimal valid 1040 — just enough to pass validation
      const page1 = makeMockPage(make1040Page1Items([
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Content ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());

      // Should not throw — just return empty fields
      expect(result.personalInfo.firstName.value).toBeDefined();
      expect(result.personalInfo.lastName.value).toBeDefined();
      expect(result.dependents).toEqual([]);
      expect(result.financials).toBeDefined();
    });

    it('should return empty dependents when no dependents section found', async () => {
      const page1 = makeMockPage(make1040Page1Items([
        ...Array.from({ length: 15 }, (_, i) =>
          makeTextItem(`Line ${i}`, 50, 600 - i * 20),
        ),
      ]));
      const page2 = makeMockPage(make1040Page2Items());
      setupMockPdf([page1, page2]);

      const result = await parseCompetitorReturn(makeFile());
      expect(result.dependents).toHaveLength(0);
    });
  });
});
