/**
 * Competitor Return Parser — extracts personal info, dependents, and financial
 * summary from a completed IRS Form 1040 PDF generated by competitor tax software.
 *
 * Two extraction strategies (tried in order):
 * 1. AcroForm fields — works on IRS fillable PDFs (rare from competitors)
 * 2. Text-based heuristics — primary path for flat (non-fillable) competitor PDFs
 *
 * All processing runs client-side. Data never leaves the browser.
 * Full SSNs are immediately truncated to last 4 — never stored in state.
 */

import * as pdfjsLib from 'pdfjs-dist';
import './pdfWorkerInit'; // Ensure worker is configured
import { FilingStatus } from '@telostax/engine';
import { MAX_PDF_SIZE } from './importHelpers';
import {
  extractTextBlocks,
  extractTextBlocksFromPages,
  parseDollarValue,
  detectTaxYear,
  find1040Pages,
  type TextBlock,
} from './pdfTextUtils';
import {
  FORM_1040_TEXT_KEYWORDS,
  FORM_1040_EXTRACT_FIELDS,
  extractAcroFormFinancials,
  extractFinancialsFromText,
} from './priorYearImporter';
import { detectProvider } from '../data/competitorProviders';

// ─── Types ─────────────────────────────────────────

export type Confidence = 'high' | 'medium' | 'low';

export interface ExtractedField<T> {
  value: T;
  confidence: Confidence;
}

export interface ExtractedDependent {
  firstName: string;
  lastName: string;
  ssnLastFour?: string;
  relationship?: string;
}

export interface CompetitorExtractResult {
  personalInfo: {
    firstName: ExtractedField<string>;
    lastName: ExtractedField<string>;
    addressStreet: ExtractedField<string>;
    addressCity: ExtractedField<string>;
    addressState: ExtractedField<string>;
    addressZip: ExtractedField<string>;
    filingStatus: ExtractedField<FilingStatus | null>;
    spouseFirstName?: ExtractedField<string>;
    spouseLastName?: ExtractedField<string>;
  };
  dependents: ExtractedDependent[];
  financials: Record<string, number>;
  detectedProvider?: string;
  detectedTaxYear: number;
  warnings: string[];
}

// ─── AcroForm personal info field names ────────────
// From irsForm1040Map.ts — only works for IRS fillable PDFs

const P1 = 'topmostSubform[0].Page1[0]';
const ADDR = `${P1}.Address_ReadOrder[0]`;
const CB = `${P1}.Checkbox_ReadOrder[0]`;

// 2025 field names (from irsForm1040Map.ts)
const PERSONAL_ACROFORM_FIELDS = {
  firstName:      `${P1}.f1_14[0]`,
  lastName:       `${P1}.f1_15[0]`,
  // SSN fields (f1_16, f1_19) intentionally excluded — never read or stored
  spouseFirstName: `${P1}.f1_17[0]`,
  spouseLastName:  `${P1}.f1_18[0]`,
  addressStreet:  `${ADDR}.f1_20[0]`,
  addressCity:    `${ADDR}.f1_22[0]`,
  addressState:   `${ADDR}.f1_23[0]`,
  addressZip:     `${ADDR}.f1_24[0]`,
} as const;

// 2024 field names (different numbering)
const PERSONAL_ACROFORM_FIELDS_2024 = {
  firstName:      `${P1}.f1_01[0]`,
  lastName:       `${P1}.f1_02[0]`,
  spouseFirstName: `${P1}.f1_04[0]`,
  spouseLastName:  `${P1}.f1_05[0]`,
  addressStreet:  `${ADDR}.f1_10[0]`,
  addressCity:    `${ADDR}.f1_12[0]`,
  addressState:   `${ADDR}.f1_13[0]`,
  addressZip:     `${ADDR}.f1_14[0]`,
} as const;

// 2025 filing status checkboxes
const FILING_STATUS_CHECKBOXES: Record<string, FilingStatus> = {
  [`${CB}.c1_8[0]`]: FilingStatus.Single,
  [`${CB}.c1_8[1]`]: FilingStatus.MarriedFilingJointly,
  [`${CB}.c1_8[2]`]: FilingStatus.MarriedFilingSeparately,
  [`${P1}.c1_8[0]`]: FilingStatus.HeadOfHousehold,
  [`${P1}.c1_8[1]`]: FilingStatus.QualifyingSurvivingSpouse,
};

// 2024 filing status checkboxes (different prefix structure)
const FS_2024 = `${P1}.FilingStatus_ReadOrder[0]`;
const FILING_STATUS_CHECKBOXES_2024: Record<string, FilingStatus> = {
  [`${FS_2024}.c1_3[0]`]: FilingStatus.Single,
  [`${FS_2024}.c1_3[1]`]: FilingStatus.MarriedFilingJointly,
  [`${FS_2024}.c1_3[2]`]: FilingStatus.MarriedFilingSeparately,
  [`${P1}.c1_3[0]`]: FilingStatus.HeadOfHousehold,
  [`${P1}.c1_3[1]`]: FilingStatus.QualifyingSurvivingSpouse,
};

// Dependent AcroForm fields (rows × 4 dependents)
const DEP_TABLE = `${P1}.Table_Dependents[0]`;
const DEP_FIRST_NAMES = [
  `${DEP_TABLE}.Row1[0].f1_31[0]`, `${DEP_TABLE}.Row1[0].f1_32[0]`,
  `${DEP_TABLE}.Row1[0].f1_33[0]`, `${DEP_TABLE}.Row1[0].f1_34[0]`,
];
const DEP_LAST_NAMES = [
  `${DEP_TABLE}.Row2[0].f1_35[0]`, `${DEP_TABLE}.Row2[0].f1_36[0]`,
  `${DEP_TABLE}.Row2[0].f1_37[0]`, `${DEP_TABLE}.Row2[0].f1_38[0]`,
];
const DEP_SSNS = [
  `${DEP_TABLE}.Row3[0].f1_39[0]`, `${DEP_TABLE}.Row3[0].f1_40[0]`,
  `${DEP_TABLE}.Row3[0].f1_41[0]`, `${DEP_TABLE}.Row3[0].f1_42[0]`,
];
const DEP_RELATIONSHIPS = [
  `${DEP_TABLE}.Row4[0].f1_43[0]`, `${DEP_TABLE}.Row4[0].f1_44[0]`,
  `${DEP_TABLE}.Row4[0].f1_45[0]`, `${DEP_TABLE}.Row4[0].f1_46[0]`,
];

// ─── US state abbreviation set ─────────────────────

const US_STATES = new Set([
  'AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN',
  'IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
  'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
  'VT','VA','WA','WV','WI','WY','AS','GU','MP','PR','VI',
]);

// ─── Main parser ───────────────────────────────────

export async function parseCompetitorReturn(file: File): Promise<CompetitorExtractResult> {
  const warnings: string[] = [];

  // ── Validate file ──
  if (file.size > MAX_PDF_SIZE) {
    throw new Error(
      `File is too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Maximum size is ${MAX_PDF_SIZE / 1024 / 1024} MB.`,
    );
  }

  // ── Open PDF ──
  let pdf: pdfjsLib.PDFDocumentProxy;
  try {
    const arrayBuffer = await file.arrayBuffer();
    pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
  } catch (err: unknown) {
    // Detect password-protected PDFs
    if (err && typeof err === 'object' && 'name' in err && (err as { name: string }).name === 'PasswordException') {
      throw new Error('This PDF is password-protected. Please remove the password and try again.');
    }
    throw new Error('Could not open this PDF. Make sure it\u2019s a valid PDF file.');
  }

  // ── Find 1040 pages (handles multi-page competitor bundles) ──
  const pages1040 = await find1040Pages(pdf);
  if (!pages1040) {
    throw new Error(
      'Could not find Form 1040 in this PDF. Make sure you uploaded your completed federal tax return (not a state return or other document).',
    );
  }

  // ── Detect scanned PDF ──
  const page1Blocks = await extractTextBlocksFromPages(pdf, [pages1040.page1]);
  if (page1Blocks.length < 10) {
    throw new Error(
      'This PDF appears to be scanned or image-based. Please download the digitally-generated PDF from your tax software instead.',
    );
  }

  // ── Detect 1040-X (amended return) ──
  const fullPage1Text = page1Blocks.map(b => b.text).join(' ').toLowerCase();
  if (fullPage1Text.includes('1040-x') || fullPage1Text.includes('amended')) {
    throw new Error(
      'This appears to be an amended return (Form 1040-X). Please upload your original Form 1040 instead.',
    );
  }

  // ── Detect "DO NOT FILE" watermark ──
  if (fullPage1Text.includes('do not file')) {
    warnings.push('This PDF contains a "DO NOT FILE" watermark. It may be a draft or sample return.');
  }

  // ── Detect provider ──
  const allBlocks = await extractTextBlocksFromPages(pdf, [pages1040.page1, pages1040.page2]);
  const allText = allBlocks.map(b => b.text).join(' ');
  const detectedProvider = detectProvider(allText);

  // ── Detect tax year ──
  const detectedTaxYear = await detectTaxYear(pdf);

  if (detectedTaxYear >= 2026) {
    warnings.push(
      `Detected tax year ${detectedTaxYear}. This appears to be a current-year return, not a prior year.`,
    );
  }

  // ── Strategy 1: Try AcroForm extraction ──
  const form1040Pages = [pages1040.page1, pages1040.page2];
  const acroPersonal = await extractAcroFormPersonalInfo(pdf, pages1040.page1);
  const acroFinancials = await extractAcroFormFinancials(pdf, form1040Pages);
  const acroDependents = await extractAcroFormDependents(pdf, pages1040.page1);
  const hasAcroPersonal = acroPersonal.firstName !== '' || acroPersonal.lastName !== '';
  const hasAcroFinancials = Object.values(acroFinancials).some(v => v !== 0);

  // ── Strategy 2: Text-based extraction (always run for personal info) ──
  const textBlocks = await extractTextBlocksFromPages(pdf, form1040Pages);
  const textPersonal = extractPersonalInfoFromText(textBlocks, pages1040.page1);
  const textDependents = extractDependentsFromText(textBlocks, pages1040.page1);

  // ── Merge personal info (prefer AcroForm if available) ──
  const personalInfo = mergePersonalInfo(
    hasAcroPersonal ? acroPersonal : null,
    textPersonal,
    warnings,
  );

  // ── Get financials ──
  let financials: Record<string, number>;
  if (hasAcroFinancials) {
    financials = acroFinancials;
  } else {
    warnings.push('Could not read form fields \u2014 fell back to text extraction for financial data. Please verify all values.');
    financials = await extractFinancialsFromText(pdf, form1040Pages);
  }

  // ── Merge dependents ──
  const dependents = hasAcroPersonal && acroDependents.length > 0
    ? acroDependents
    : textDependents;

  // ── Filing status from text if AcroForm didn't get it ──
  if (personalInfo.filingStatus.value === null) {
    const textFS = detectFilingStatusFromText(textBlocks);
    if (textFS !== null) {
      personalInfo.filingStatus = { value: textFS, confidence: 'medium' };
    }
  }

  return {
    personalInfo,
    dependents,
    financials,
    detectedProvider,
    detectedTaxYear,
    warnings,
  };
}

// ─── AcroForm personal info extraction ─────────────

interface RawAcroPersonal {
  firstName: string;
  lastName: string;
  spouseFirstName: string;
  spouseLastName: string;
  addressStreet: string;
  addressCity: string;
  addressState: string;
  addressZip: string;
  filingStatus: FilingStatus | null;
}

async function extractAcroFormPersonalInfo(
  pdf: pdfjsLib.PDFDocumentProxy,
  page1Num: number,
): Promise<RawAcroPersonal> {
  const result: RawAcroPersonal = {
    firstName: '', lastName: '', spouseFirstName: '', spouseLastName: '',
    addressStreet: '', addressCity: '', addressState: '',
    addressZip: '', filingStatus: null,
  };

  try {
    const page = await pdf.getPage(page1Num);
    const annotations = await page.getAnnotations();

    for (const annot of annotations) {
      if (annot.subtype !== 'Widget' || !annot.fieldName) continue;
      const fname = annot.fieldName;
      const val = typeof annot.fieldValue === 'string' ? annot.fieldValue.trim() : '';

      // Personal info fields — try both 2025 and 2024 field names
      for (const fields of [PERSONAL_ACROFORM_FIELDS, PERSONAL_ACROFORM_FIELDS_2024]) {
        for (const [key, pdfField] of Object.entries(fields)) {
          if (fname === pdfField && val) {
            result[key as keyof typeof PERSONAL_ACROFORM_FIELDS] = val;
          }
        }
      }

      // Filing status checkboxes — try both 2025 and 2024 field names
      for (const cbMap of [FILING_STATUS_CHECKBOXES, FILING_STATUS_CHECKBOXES_2024]) {
        for (const [pdfField, status] of Object.entries(cbMap)) {
          if (fname === pdfField && annot.fieldValue) {
            const cbVal = String(annot.fieldValue);
            if (cbVal && cbVal !== 'Off' && cbVal !== '0') {
              result.filingStatus = status;
            }
          }
        }
      }
    }
  } catch {
    // AcroForm not available — text fallback will handle it
  }

  return result;
}

// ─── AcroForm dependents extraction ────────────────

async function extractAcroFormDependents(
  pdf: pdfjsLib.PDFDocumentProxy,
  page1Num: number,
): Promise<ExtractedDependent[]> {
  const deps: ExtractedDependent[] = [];

  try {
    const page = await pdf.getPage(page1Num);
    const annotations = await page.getAnnotations();

    const fieldMap = new Map<string, string>();
    for (const annot of annotations) {
      if (annot.subtype !== 'Widget' || !annot.fieldName) continue;
      const val = typeof annot.fieldValue === 'string' ? annot.fieldValue.trim() : '';
      if (val) fieldMap.set(annot.fieldName, val);
    }

    for (let i = 0; i < 4; i++) {
      const firstName = fieldMap.get(DEP_FIRST_NAMES[i]) || '';
      const lastName = fieldMap.get(DEP_LAST_NAMES[i]) || '';
      if (!firstName && !lastName) continue;

      const rawSsn = fieldMap.get(DEP_SSNS[i]) || '';
      const relationship = fieldMap.get(DEP_RELATIONSHIPS[i]) || '';

      deps.push({
        firstName,
        lastName,
        ssnLastFour: sanitizeSsnToLastFour(rawSsn),
        relationship: relationship || undefined,
      });
    }
  } catch {
    // Gracefully degrade — text fallback handles it
  }

  return deps;
}

// ─── Text-based personal info extraction ───────────

interface TextPersonal {
  firstName: string;
  lastName: string;
  addressStreet: string;
  addressCity: string;
  addressState: string;
  addressZip: string;
  filingStatus: FilingStatus | null;
  spouseFirstName: string;
  spouseLastName: string;
}

function extractPersonalInfoFromText(blocks: TextBlock[], page1Num: number): TextPersonal {
  const result: TextPersonal = {
    firstName: '', lastName: '', addressStreet: '', addressCity: '',
    addressState: '', addressZip: '', filingStatus: null,
    spouseFirstName: '', spouseLastName: '',
  };

  // Filter to page 1 blocks only
  const p1Blocks = blocks.filter(b => b.page === page1Num);
  if (p1Blocks.length === 0) return result;

  // Sort by y position (top to bottom)
  const sortedByY = [...p1Blocks].sort((a, b) => a.y - b.y);

  // ── Address extraction: anchor on ZIP pattern ──
  // ZIP codes are highly reliable anchors — \b\d{5}(-\d{4})?\b
  // Instruction text like "more than half of 2025" contains digits — must be filtered out.
  const INSTRUCTION_TEXT = /more than half|see instructions|check here|check if|see separate|election campaign|presidential|do not write|for disclosure/i;
  const FORM_LABEL_TEXT = /^(state|zip\s*code|city|town|apt\.?\s*no|foreign|foreign\s+postal\s+code|foreign\s+province.*|foreign\s+country\s+name|home\s+address|post\s+office|city,?\s+town.*)$/i;

  for (const block of p1Blocks) {
    const zipMatch = block.text.match(/\b(\d{5})(-\d{4})?\b/);
    if (!zipMatch) continue;

    // Skip blocks that are clearly instruction/label text
    if (INSTRUCTION_TEXT.test(block.text)) continue;

    const zip = zipMatch[0];
    // Validate it's plausibly a ZIP (not a dollar amount or SSN fragment)
    const zipNum = parseInt(zip.substring(0, 5), 10);
    if (zipNum >= 501 && zipNum <= 99950) {
      result.addressZip = zip;

      // Look for state abbreviation near the ZIP (same line ±30px)
      const nearbyBlocks = p1Blocks.filter(b =>
        b.page === block.page &&
        Math.abs(b.y - block.y) < 30 &&
        b !== block &&
        !INSTRUCTION_TEXT.test(b.text) &&
        !FORM_LABEL_TEXT.test(b.text.trim()),
      );

      for (const nearby of nearbyBlocks) {
        // Check for 2-letter state abbreviation
        const stateMatch = nearby.text.match(/\b([A-Z]{2})\b/);
        if (stateMatch && US_STATES.has(stateMatch[1])) {
          result.addressState = stateMatch[1];

          // The text before the state abbreviation on the same block might be the city
          const beforeState = nearby.text.substring(0, nearby.text.indexOf(stateMatch[1])).trim();
          if (beforeState) {
            // Remove trailing comma or space
            result.addressCity = beforeState.replace(/[,\s]+$/, '');
          }
          break;
        }
      }

      // If city wasn't found in the state block, look at blocks on the same line to the left.
      // Use tight Y tolerance (10px) — city must be on the same line as ZIP, not just nearby.
      if (!result.addressCity) {
        const leftBlocks = nearbyBlocks
          .filter(b => b.x < block.x && Math.abs(b.y - block.y) < 10)
          .sort((a, b) => b.x - a.x); // rightmost first

        for (const lb of leftBlocks) {
          if (FORM_LABEL_TEXT.test(lb.text.trim())) continue;
          // Skip standalone state abbreviations (already extracted as addressState)
          if (US_STATES.has(lb.text.trim())) continue;
          // Skip if it's "city, state" combined
          if (lb.text.includes(',')) {
            const parts = lb.text.split(',');
            const cityCandidate = parts[0].trim();
            const stateCandidate = parts[1]?.trim().toUpperCase();
            if (US_STATES.has(stateCandidate)) {
              result.addressCity = cityCandidate;
              result.addressState = stateCandidate;
              break;
            }
          }
          // Pure city name
          if (lb.text.length > 1 && !/^\d+$/.test(lb.text)) {
            result.addressCity = lb.text.replace(/[,\s]+$/, '');
            break;
          }
        }
      }

      // ── Street address: look for blocks above the city/ZIP line ──
      // Street addresses are typically 1 line above city/state/ZIP
      const zipY = block.y;
      const streetCandidates = p1Blocks
        .filter(b =>
          b.page === block.page &&
          b.y < zipY - 5 && // above the ZIP line
          b.y > zipY - 60 && // but not too far above
          b.x < 450 && // address field is left of Apt. no. — excludes Presidential Election Campaign column
          /\d/.test(b.text) && // street addresses contain numbers
          b.text.length > 3 &&
          !INSTRUCTION_TEXT.test(b.text) &&
          !FORM_LABEL_TEXT.test(b.text.trim()),
        )
        .sort((a, b) => b.y - a.y); // closest to ZIP first

      if (streetCandidates.length > 0) {
        result.addressStreet = streetCandidates[0].text;
      }

      break; // Use first ZIP match
    }
  }

  // ── Name extraction: look for text in the header region ──
  // Names are typically in the top portion of page 1, before the address
  // IRS 1040 has "Your first name and middle initial" and "Last name" as labels

  // Known 1040 form labels that appear near name/address fields and must be excluded
  const FORM_LABEL_BLOCKLIST = /^(deceased|spouse|combat\s*zone|see\s+(separate\s+)?instructions|your\s+social|social\s+security|filing\s+status|check\s+(only|here|if)|standard\s+deduction|head\s+of|qualifying|married|single|other|apt\.?\s*no|state|zip\s*code|foreign|presidential|city|town|post\s+office)$/i;

  const isFormLabel = (text: string) => FORM_LABEL_BLOCKLIST.test(text.trim());

  const headerBlocks = sortedByY.filter(b => b.y < (result.addressZip ? getBlockByText(p1Blocks, result.addressZip)?.y ?? 200 : 200));

  // Look for name labels
  const firstNameLabel = p1Blocks.find(b =>
    b.text.toLowerCase().includes('first name') || b.text.toLowerCase().includes('your first'),
  );

  // Date format placeholders (from "Deceased MM/DD/YYYY" header) that
  // can appear near name labels and must not be treated as names
  const DATE_PLACEHOLDER_BLOCKLIST = /^(MM|DD|YYYY|MM\/DD\/YYYY|DD\/MM\/YYYY)$/;

  if (firstNameLabel) {
    // On IRS 1040, values appear ABOVE their labels (~15px).
    // Use directional filter: only look above the label (+ 2px buffer) to avoid
    // picking up spouse values from the row below.
    const nameCandidates = p1Blocks.filter(b =>
      b.page === firstNameLabel.page &&
      b.y < firstNameLabel.y + 2 && b.y > firstNameLabel.y - 20 &&
      b.x > firstNameLabel.x &&
      b !== firstNameLabel &&
      !/first name|last name|middle|initial/i.test(b.text) &&
      !isFormLabel(b.text) &&
      !DATE_PLACEHOLDER_BLOCKLIST.test(b.text.trim()) &&
      !/^\d/.test(b.text), // not a number (SSN field)
    );

    if (nameCandidates.length > 0) {
      // Sort left to right
      nameCandidates.sort((a, b) => a.x - b.x);
      const nameText = nameCandidates[0].text.trim();
      // Could be "John M" (first + middle initial)
      const parts = nameText.split(/\s+/);
      result.firstName = parts[0] || '';
    }
  }

  // Look for last name
  const lastNameLabel = p1Blocks.find(b =>
    b.text.toLowerCase().includes('last name') &&
    !b.text.toLowerCase().includes('spouse'),
  );

  if (lastNameLabel) {
    const candidates = p1Blocks.filter(b =>
      b.page === lastNameLabel.page &&
      b.y < lastNameLabel.y + 2 && b.y > lastNameLabel.y - 20 &&
      b.x > lastNameLabel.x &&
      b !== lastNameLabel &&
      !/last name|suffix/i.test(b.text) &&
      !isFormLabel(b.text) &&
      !DATE_PLACEHOLDER_BLOCKLIST.test(b.text.trim()) &&
      !/^\d/.test(b.text) &&
      !/^[,.;:]/.test(b.text.trim()) && // exclude header fragments like ", 2024, ending"
      // Exclude the already-extracted first name (it may overlap the last name column
      // due to form field text positioning in flattened PDFs)
      b.text.trim() !== result.firstName,
    );

    if (candidates.length > 0) {
      candidates.sort((a, b) => a.x - b.x);
      result.lastName = candidates[0].text.trim();
    }
  }

  // ── Spouse name extraction ──
  const spouseLabel = p1Blocks.find(b =>
    b.text.toLowerCase().includes('spouse') &&
    (b.text.toLowerCase().includes('first') || b.text.toLowerCase().includes('name')),
  );

  if (spouseLabel) {
    // Spouse values are above the spouse label (~12px), same as primary name layout.
    // Use directional filter + relaxed x threshold (text may be slightly left of label).
    const spouseCandidates = p1Blocks.filter(b =>
      b.page === spouseLabel.page &&
      b.y < spouseLabel.y + 2 && b.y > spouseLabel.y - 20 &&
      b.x > spouseLabel.x - 10 &&
      b !== spouseLabel &&
      !/spouse|first|last|name|middle|initial/i.test(b.text) &&
      !isFormLabel(b.text) &&
      !DATE_PLACEHOLDER_BLOCKLIST.test(b.text.trim()) &&
      !/^\d/.test(b.text) &&
      !/^[,.;:]/.test(b.text.trim()),
    );

    if (spouseCandidates.length > 0) {
      spouseCandidates.sort((a, b) => a.x - b.x);
      result.spouseFirstName = spouseCandidates[0].text.split(/\s+/)[0] || '';
    }

    // Spouse last name — find the "Last name" label on the spouse row
    const spouseLastLabel = p1Blocks.find(b =>
      b.page === spouseLabel.page &&
      Math.abs(b.y - spouseLabel.y) < 5 &&
      b.text.toLowerCase().includes('last name') &&
      b !== spouseLabel,
    );

    if (spouseLastLabel) {
      const lastCandidates = p1Blocks.filter(b =>
        b.page === spouseLastLabel.page &&
        b.y < spouseLastLabel.y + 2 && b.y > spouseLastLabel.y - 20 &&
        b.x > spouseLastLabel.x &&
        b !== spouseLastLabel &&
        !/last name|suffix|spouse/i.test(b.text) &&
        !isFormLabel(b.text) &&
        !DATE_PLACEHOLDER_BLOCKLIST.test(b.text.trim()) &&
        !/^\d/.test(b.text) &&
        !/^[,.;:]/.test(b.text.trim()) &&
        b.text.trim() !== result.spouseFirstName,
      );

      if (lastCandidates.length > 0) {
        lastCandidates.sort((a, b) => a.x - b.x);
        result.spouseLastName = lastCandidates[0].text.trim();
      }
    }
  }

  // ── Filing status from text ──
  result.filingStatus = detectFilingStatusFromText(blocks);

  return result;
}

// ─── Text-based dependent extraction ───────────────

function extractDependentsFromText(blocks: TextBlock[], page1Num: number): ExtractedDependent[] {
  const deps: ExtractedDependent[] = [];
  const p1Blocks = blocks.filter(b => b.page === page1Num);

  // Look for "Dependents" section label
  const depLabel = p1Blocks.find(b =>
    b.text.toLowerCase().includes('dependents') &&
    !b.text.toLowerCase().includes('claimed'),
  );

  if (!depLabel) return deps;

  // Dependent data is below the label, in a tabular region.
  // Exclude sidebar instruction blocks (x < 80) like "If more", "than four",
  // "see instructions", etc. that can contaminate row grouping.
  // Use 65px height to avoid picking up Income section lines below the table.
  const depRegionBlocks = p1Blocks
    .filter(b =>
      b.y > depLabel.y &&
      b.y < depLabel.y + 65 && // dependents table only — excludes income section
      b.x >= 80 && // exclude left-sidebar instruction fragments
      b.text.length > 1,
    )
    .sort((a, b) => a.y - b.y);

  if (depRegionBlocks.length === 0) return deps;

  // Group blocks by approximate Y coordinate (rows)
  const rows: TextBlock[][] = [];
  let currentRow: TextBlock[] = [];
  let currentY = depRegionBlocks[0].y;

  for (const block of depRegionBlocks) {
    if (Math.abs(block.y - currentY) > 8) {
      if (currentRow.length > 0) rows.push(currentRow);
      currentRow = [];
      currentY = block.y;
    }
    currentRow.push(block);
  }
  if (currentRow.length > 0) rows.push(currentRow);

  // Each row of the dependent table has: name, SSN, relationship, checkbox(es)
  for (const row of rows) {
    // Sort left to right
    row.sort((a, b) => a.x - b.x);

    // Skip label/header rows and instruction text
    const rowText = row.map(b => b.text).join(' ').toLowerCase();
    if (
      rowText.includes('first name') ||
      rowText.includes('last name') ||
      rowText.includes('social security') ||
      rowText.includes('relationship') ||
      rowText.includes('credit for') ||
      rowText.includes('child tax') ||
      // Filter out IRS dependent table instruction fragments
      rowText.includes('if more') ||
      rowText.includes('than four') ||
      rowText.includes('see instructions') ||
      rowText.includes('and check') ||
      rowText.includes('check if') ||
      rowText.includes('full-time') ||
      rowText.includes('student') ||
      rowText.includes('permanently') ||
      rowText.includes('disabled') ||
      rowText.includes('dependents,') ||
      /^\(\d\)/.test(rowText.trim()) || // "(1) First name", "(6) Check if"
      /^dependent\s+\d/.test(rowText.trim()) // "Dependent 1", "Dependent 2"
    ) {
      continue;
    }

    // Try to extract name from the row
    const nameBlocks = row.filter(b =>
      !/^\d{3}[-\s]?\d{2}[-\s]?\d{4}$/.test(b.text) && // not an SSN
      !/^\d+$/.test(b.text) && // not a pure number
      !/^[xX✓✔]$/.test(b.text) && // not a checkbox mark
      !/^(yes|no|and|or|the|if|with|you|more|here|check|see|lived|half)$/i.test(b.text) && // not common instruction words
      !/^\(\d\)/.test(b.text) && // not "(1)", "(6)" etc.
      b.text.length > 1,
    );

    if (nameBlocks.length === 0) continue;

    // First text block is likely the dependent's name
    const nameParts = nameBlocks[0].text.split(/\s+/);
    const firstName = nameParts[0] || '';
    const lastName = nameParts.length > 1 ? nameParts.slice(1).join(' ') : (nameBlocks[1]?.text || '');

    if (!firstName) continue;

    // Look for SSN in the row (extract last 4 only)
    const ssnBlock = row.find(b => /\d{3}[-\s]?\d{2}[-\s]?\d{4}/.test(b.text));
    const ssnLastFour = ssnBlock ? sanitizeSsnToLastFour(ssnBlock.text) : undefined;

    // Look for relationship keyword
    const relationships = ['son', 'daughter', 'child', 'stepchild', 'foster', 'brother', 'sister', 'parent', 'grandchild', 'niece', 'nephew', 'other'];
    let relationship: string | undefined;
    for (const block of nameBlocks) {
      const lower = block.text.toLowerCase();
      for (const rel of relationships) {
        if (lower.includes(rel)) {
          relationship = block.text;
          break;
        }
      }
    }

    deps.push({ firstName, lastName, ssnLastFour, relationship });
  }

  return deps;
}

// ─── Filing status detection ───────────────────────

/**
 * Filing status labels and their Y-range on the IRS 1040.
 * Every 1040 prints all 5 labels — we must detect which is CHECKED (has an "X" nearby).
 */
const FILING_STATUS_LABELS: Array<{ pattern: RegExp; status: FilingStatus }> = [
  { pattern: /\bsingle\b/i, status: FilingStatus.Single },
  { pattern: /married filing jointly/i, status: FilingStatus.MarriedFilingJointly },
  { pattern: /married filing separately|filing separately.*mfs/i, status: FilingStatus.MarriedFilingSeparately },
  { pattern: /head of household/i, status: FilingStatus.HeadOfHousehold },
  { pattern: /qualifying surviving spouse|qualifying widow/i, status: FilingStatus.QualifyingSurvivingSpouse },
];

function detectFilingStatusFromText(blocks: TextBlock[]): FilingStatus | null {
  // Strategy 1: Look for checkmarks (X, ✓, ✔, ☒) near filing status labels.
  // On flat (non-fillable) PDFs, the checked status has an "X" rendered as a
  // text item to the left of or very close to the label.
  // On some flattened PDFs the checkbox is rendered as its ordinal digit
  // (e.g. "1" for Single, "4" for Head of Household) — include single digits.
  const checkChars = /^[xX✓✔☒■◼⊠1-5]$/;

  // Find all check-mark blocks in the filing status region (top portion of page)
  const checkBlocks = blocks.filter(b =>
    checkChars.test(b.text.trim()) && b.y < 350,
  );

  if (checkBlocks.length > 0) {
    // Find the filing status label with the closest checkmark.
    // We can't return on the first match because labels like "Single" and
    // "Married filing jointly" are stacked vertically at the same x position,
    // so a nearby checkmark can fall within the y-threshold of both.
    let bestStatus: FilingStatus | null = null;
    let bestDist = Infinity;

    for (const { pattern, status } of FILING_STATUS_LABELS) {
      const labelBlock = blocks.find(b => pattern.test(b.text) && b.y < 350);
      if (!labelBlock) continue;

      for (const cb of checkBlocks) {
        if (cb.page !== labelBlock.page) continue;
        const yDist = Math.abs(cb.y - labelBlock.y);
        if (yDist >= 20) continue; // not on same line
        if (cb.x > labelBlock.x + 10) continue; // checkmark must be to the left

        if (yDist < bestDist) {
          bestDist = yDist;
          bestStatus = status;
        }
      }
    }

    if (bestStatus !== null) return bestStatus;
  }

  // Strategy 2: If only ONE filing status label appears (some competitor PDFs
  // only render the selected status), it must be the selected one.
  // If multiple appear (standard IRS 1040 prints all 5), we can't determine
  // which is selected without checkmarks — fall through to Strategy 3.
  const matchedStatuses: FilingStatus[] = [];
  for (const { pattern, status } of FILING_STATUS_LABELS) {
    const matchBlock = blocks.find(b =>
      pattern.test(b.text) &&
      b.y < 350 &&
      b.text.length < 50,
    );
    if (matchBlock) matchedStatuses.push(status);
  }

  if (matchedStatuses.length === 1) {
    return matchedStatuses[0];
  }

  // Strategy 3 (fallback): Use abbreviation keywords that only appear
  // when a status is actually selected (not as a printed label)
  const text = blocks.map(b => b.text).join(' ').toLowerCase();
  if (/\bmfj\b/.test(text)) return FilingStatus.MarriedFilingJointly;
  if (/\bmfs\b/.test(text)) return FilingStatus.MarriedFilingSeparately;
  if (/\bhoh\b/.test(text)) return FilingStatus.HeadOfHousehold;
  if (/\bqss\b/.test(text)) return FilingStatus.QualifyingSurvivingSpouse;

  return null;
}

// ─── Merge personal info ───────────────────────────

function mergePersonalInfo(
  acro: RawAcroPersonal | null,
  text: TextPersonal,
  warnings: string[],
): CompetitorExtractResult['personalInfo'] {
  const pick = <T extends string>(
    acroVal: string | undefined,
    textVal: string,
  ): ExtractedField<T> => {
    if (acroVal) {
      return { value: acroVal as T, confidence: 'high' };
    }
    if (textVal) {
      return { value: textVal as T, confidence: 'medium' };
    }
    return { value: '' as T, confidence: 'low' };
  };

  const result: CompetitorExtractResult['personalInfo'] = {
    firstName: pick(acro?.firstName, text.firstName),
    lastName: pick(acro?.lastName, text.lastName),
    addressStreet: pick(acro?.addressStreet, text.addressStreet),
    addressCity: pick(acro?.addressCity, text.addressCity),
    addressState: pick(acro?.addressState, text.addressState),
    addressZip: pick(acro?.addressZip, text.addressZip),
    filingStatus: acro?.filingStatus !== null && acro?.filingStatus !== undefined
      ? { value: acro.filingStatus, confidence: 'high' }
      : text.filingStatus !== null
        ? { value: text.filingStatus, confidence: 'medium' }
        : { value: null, confidence: 'low' },
  };

  // Spouse info — suppress when the filing status definitively indicates no spouse.
  // HOH, Single, and QSS filers should never have spouse fields populated
  // (on flattened 1040s the spouse name labels are printed for everyone, so
  // text extraction can erroneously pick up nearby form text as spouse names).
  // When filing status is null (unknown), we still allow spouse info through.
  const fsValue = result.filingStatus.value;
  const noSpouseStatus =
    fsValue === FilingStatus.Single ||
    fsValue === FilingStatus.HeadOfHousehold ||
    fsValue === FilingStatus.QualifyingSurvivingSpouse;

  if (!noSpouseStatus) {
    const spouseFirst = acro?.spouseFirstName || text.spouseFirstName;
    const spouseLast = acro?.spouseLastName || text.spouseLastName;

    if (spouseFirst) {
      result.spouseFirstName = {
        value: spouseFirst,
        confidence: acro?.spouseFirstName ? 'high' : 'medium',
      };
    }
    if (spouseLast) {
      result.spouseLastName = {
        value: spouseLast,
        confidence: acro?.spouseLastName ? 'high' : 'medium',
      };
    }
  }

  // Track low-confidence fields
  const lowConfFields = Object.entries(result)
    .filter(([, field]) => field && typeof field === 'object' && 'confidence' in field && field.confidence === 'low' && field.value !== '' && field.value !== null)
    .map(([key]) => key);

  if (lowConfFields.length > 0) {
    warnings.push(`Low confidence on: ${lowConfFields.join(', ')}. Please verify these fields.`);
  }

  return result;
}

// ─── Helpers ───────────────────────────────────────

/**
 * Sanitize an SSN string to only the last 4 digits.
 * SECURITY: Full SSNs are never stored — only last 4 are retained.
 */
export function sanitizeSsnToLastFour(raw: string): string | undefined {
  const digits = raw.replace(/\D/g, '');
  if (digits.length >= 4) {
    return digits.slice(-4);
  }
  return undefined;
}

/** Find a block by its text content */
function getBlockByText(blocks: TextBlock[], text: string): TextBlock | undefined {
  return blocks.find(b => b.text.includes(text));
}
